{
  "openapi":"3.0.2",

  "info": {
    "title":"APONTA- API",
    "description": "Essa API é um gerenciador de agendamentos genérico, tendo em vista que está sendo elaborado como o projeto de conclusão de curso de Gabriel José Silva.",
    "contact": {
      "name": "Gabriel Silva",
      "email": "contato.gabrieljosesilva@gmail.com",
      "url": "https://github.com/gabriellgjs"
    },
    "version":"1.0.0"
  },
  "servers": [
    {
      "url":"http://localhost:3000/v1/"
    }
  ],
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },

  "paths": {
    "/login": {
      "post": {
        "tags": ["Autenticação"],
        "summary": "Realizar login",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "teste@email.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login realizado com sucesso"
            },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Email ou senha inválidos"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/roles": {
      "get": {
        "summary": "Buscar todos os cargos",
        "tags": ["Cargos"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "responses": {
          "200": {
            "description": "Array de objeto dos cargos"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },

      "post": {
        "summary": "Criar um novo cargo",
        "tags": ["Cargos"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Teste"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Id do cargo criado"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/roles/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "description": "Insira o id"
        }
      ],
      "get": {
        "summary": "Buscar cargo pelo id",
        "tags": ["Cargos"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],


        "responses": {
          "200": {
            "description": "Um objeto de cargo"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },
      "put": {
        "summary": "Atualizar cargo pelo id",
        "tags": ["Cargos"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },
      "delete": {
        "summary": "Deletar cargo pelo id",
        "tags": ["Cargos"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],

        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/employees": {
      "get": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Funcionário"],
        "summary": "Buscar todos os funcionários",
        "responses": {
          "200": {
            "description": "Array de objeto dos funcionários"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },

      "post": {
        "summary": "Criar um novo funcionário",
        "tags": ["Funcionário"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Maria Silva"
                  },

                  "birthDate": {
                    "type": "string",
                    "example": "2002-12-31"
                  },


                  "rg": {
                    "type": "string",
                    "example": "123456890"
                  },

                  "cpf": {
                    "type": "string",
                    "example": "123.456.789-10"
                  },

                  "maritalStatus": {
                    "type": "string",
                    "example": "Solteiro (a)"
                  },

                  "gender": {
                    "type": "string",
                    "example": "Masculino"
                  },

                  "hireDate": {
                    "type": "string",
                    "example": "2022-12-31"
                  },

                  "user": {
                    "type": "object",
                    "example":  {
                      "email": "abc@gmail.com",
                      "password": "123456",
                      "roleId": 1
                    }
                  },

                  "address": {
                    "type": "object",
                    "example":  {
                      "street": "Rua Floresta",
                      "number": "50",
                      "district": "Jardim Panorama",
                      "city": "Altônia",
                      "postalCode": "87550-000",
                      "state": "PR"
                    }
                  },

                  "telephone": {
                    "type": "object",
                    "example":  {
                      "telephoneNumber": "(44) 99873-9002"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Id do funcionário criado"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/employees/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "description": "Buscar pelo id"
        }
      ],
      "get": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Funcionário"],
        "summary": "Buscar funcionário pelo id",
        "responses": {
          "200": {
            "description": "Um objeto do funcionário"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },
      "patch": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Funcionário"],
        "summary": "Alterar o status funcionário pelo id",
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/employees/email/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "description": "Buscar pelo id"
        }
      ],
      "put": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Funcionário"],
        "summary": "Alterar o email funcionário pelo id",

        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "testantoesseemail@email.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },

    "/employees/password/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "description": "Buscar pelo id"
        }
      ],
      "put": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Funcionário"],
        "summary": "Alterar o senha funcionário pelo id",

        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "currentPassword": {
                    "type": "string",
                    "example": "123456"
                  },
                  "newPassword": {
                    "type": "string",
                    "example": "a1b2c3d4"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    },


    "/patients": {
      "get": {
        "security": [
          {
            "BearerAuth": [
              "BearerAuth"
            ]
          }
        ],
        "tags": [
          "Paciente"
        ],
        "summary": "Buscar todos os pacientes",
        "responses": {
          "200": {
            "description": "Array de objeto dos pacientes"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },

      "post": {
        "summary": "Criar um novo paciente",
        "tags": ["Paciente"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Maria Silva"
                  },

                  "birthDate": {
                    "type": "string",
                    "example": "2002-12-31"
                  },


                  "rg": {
                    "type": "string",
                    "example": "123456890"
                  },

                  "cpf": {
                    "type": "string",
                    "example": "123.456.789-10"
                  },

                  "maritalStatus": {
                    "type": "string",
                    "example": "Solteiro (a)"
                  },

                  "gender": {
                    "type": "string",
                    "example": "Masculino"
                  },

                  "address": {
                    "type": "object",
                    "example":  {
                      "street": "Rua Floresta",
                      "number": "50",
                      "district": "Jardim Panorama",
                      "city": "Altônia",
                      "postalCode": "87550-000",
                      "state": "PR"
                    }
                  },

                  "telephone": {
                    "type": "object",
                    "example":  {
                      "telephoneNumber": "(44) 99873-9002"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Id do paciente criado"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
  },

    "/patients/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "description": "Buscar pelo id"
        }
      ],
      "get": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Paciente"],
        "summary": "Buscar paciente pelo id",
        "responses": {
          "200": {
            "description": "Um objeto do paciente"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },
      "patch": {
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "tags": ["Paciente"],
        "summary": "Alterar o status paciente pelo id",
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      },

      "put": {
        "summary": "Atualizar um paciente",
        "tags": ["Paciente"],
        "security": [
          {"BearerAuth" :  ["BearerAuth"]}
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Maria Silva"
                  },

                  "birthDate": {
                    "type": "string",
                    "example": "2002-12-31"
                  },


                  "rg": {
                    "type": "string",
                    "example": "123456890"
                  },

                  "cpf": {
                    "type": "string",
                    "example": "123.456.789-10"
                  },

                  "maritalStatus": {
                    "type": "string",
                    "example": "Solteiro (a)"
                  },

                  "gender": {
                    "type": "string",
                    "example": "Masculino"
                  },

                  "address": {
                    "type": "object",
                    "example":  {
                      "street": "Rua Floresta",
                      "number": "50",
                      "district": "Jardim Panorama",
                      "city": "Altônia",
                      "postalCode": "87550-000",
                      "state": "PR"
                    }
                  },

                  "telephone": {
                    "type": "object",
                    "example":  {
                      "telephoneNumber": "(44) 99873-9002"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Sem conteúdo"
          },
          "400": {
            "description": "Conteúdo inválido"
          },
          "401": {
            "description": "Acesso negado"
          },
          "500": {
            "description": "Erro do servidor"
          }
        }
      }
    }
  }
}